# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: misha2004
      POSTGRES_DB: restaurant
    ports: 
    - 8000:8000
