import Header from "@/components/Header/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import { twMerge } from "tailwind-merge";
import Footer from "@/components/Footer/Footer";
import Alert from "@/components/ui/Alert/Alert";
import AuthProvider from "@/components/AuthProvider/AuthProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">


      <body className={twMerge(inter.className)}>
      <AuthProvider>
        
        <Alert/>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </AuthProvider>
      </body>

    </html>

  );
}
